"""empty message

Revision ID: ac1954370a5c
Revises: 4637c2cac2be
Create Date: 2025-07-03 22:03:02.822527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1954370a5c'
down_revision = '4637c2cac2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
